### ISSUE TITLE
Unable to get Steam WebAPI Key

### ISSUE THREAD

**Issue by PBotZerg** [Alex7Kom/node-steam-tradeoffers#108]
I tried to get my trade offers by using getOffers but it responded with a 403 error. The FAQ says this is an error with my API key. I tried to debug the getAPIKey method by adding a couple of log statements.
```
function getAPIKey(callback) {
console.log('     getAPIKey1');
  if (this.APIKey) {
    if (typeof callback == 'function') {
      callback();
    }
    return;
  }
console.log('     getAPIKey2');
  this._request.get({
    uri: 'https://steamcommunity.com/dev/apikey'
  }, function(error, response, body) {
console.log('     getAPIKey3');
    if (error || response.statusCode != 200) {
      this.emit('debug', 'retrieving apikey: ' + (error || response.statusCode));
      if (typeof callback == 'function') {
        callback(error || new Error(response.statusCode));
      }
      return;
    }

    var $ = cheerio.load(body);

    if ($('#mainContents h2').html() == 'Access Denied') {
      this.emit('debug', 'retrieving apikey: access denied (probably limited account)');
      var accessError = new Error('Access Denied');
      if (typeof callback == 'function') {
        return callback(accessError);
      } else {
        throw accessError;
      }
    }
    if ($('#bodyContents_ex h2').html() == 'Your Steam Web API Key') {
      var key = $('#bodyContents_ex p').html().split(' ')[1];
      this.APIKey = key;
      if (typeof callback == 'function') {
        callback();
      }
      return;
    }

    this._request.post({
      uri: 'https://steamcommunity.com/dev/registerkey',
      form: {
        domain: 'localhost',
        agreeToTerms: 1
      }
    }, function(error, response, body) {
      getAPIKey.bind(this)(callback);
    }.bind(this));
  }.bind(this));
console.log('     getAPIKey4');
}
```

Output when running:
```
C:\Users\Ryan\Desktop\nodejs>node example.js
socket timed out
socket closed
connecting to 72.165.61.188:27018
socket timed out
socket closed
connecting to 146.66.152.13:27019
connected
encrypt request
handshake complete
Logged in!
     getAPIKey1
     getAPIKey2
     getAPIKey4
error: Error: 403
undefined
C:\Users\Ryan\Desktop\nodejs\example.js:80
      if(body.response.trade_offers_received){
             ^
TypeError: Cannot read property 'response' of undefined
    at C:\Users\Ryan\Desktop\nodejs\example.js:80:14
    at Object.doAPICall.bind.callback (C:\Users\Ryan\Desktop\nodejs\node_modules
\steam-tradeoffers\index.js:268:16)
    at SteamTradeOffers.<anonymous> (C:\Users\Ryan\Desktop\nodejs\node_modules\s
team-tradeoffers\index.js:245:17)
    at Request.self.callback (C:\Users\Ryan\Desktop\nodejs\node_modules\steam-tr
adeoffers\node_modules\request\request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\Ryan\Desktop\nodejs\node_modules\steam-trad
eoffers\node_modules\request\request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\Ryan\Desktop\nodejs\node_modules\st
eam-tradeoffers\node_modules\request\request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```
I think the get request doesn't have a callback to process? I'm not sure how to proceed fixing this.

**Comment by Lwatt** [comment]
As I said on another issue - have you actually registered for an API key on the bot's account?

**Comment by srabouin** [comment]
The script is supposed to do it for you though, so something is broken

**Comment by scholtzm** [comment]
Judging by the amount of people who couldn't get 'bp.tf automatic' running (first time users without API key), seems like the initial registration of API key has changed and the code in this module no longer works.

**Comment by Alex7Kom** [comment]
Should be fixed in https://github.com/Alex7Kom/node-steam-tradeoffers/commit/3b95fdc30491caf48a2dddd7873ffd1301bed8c2. Please check if this works for you.

**Comment by scholtzm** [comment]
Since you are fixing things, is there any reason why [setup](https://github.com/Alex7Kom/node-steam-tradeoffers/#setupoptions-callback) doesn't allow to pass the API key manually in the `options` object?

**Comment by Alex7Kom** [comment]
Because it would only create confusion. You can't use the API key from another account so there is no point anyway. Maybe the only reason to allow this is to enable caching of the API key for faster restart. Is this really important?

**Comment by scholtzm** [comment]
As you said, caching. It lets you skip piece of code which essentially always returns the same response anyway. Optional feature, but useful imo. And honestly, this isn't confusing at all. This module is aimed at programmers after all.

**Comment by Alex7Kom** [comment]
The next major version will feature this, along with other significant changes, thanks.
