### ISSUE TITLE
getItems(options, callback)

### ISSUE THREAD

**Issue by Commanche2** [Alex7Kom/node-steam-tradeoffers#110]
I get everytime the same error when i try to get the items of an accepted trade that I sent:

```
Error: No session
    at Request._callback (/Users/*****/node_modules/steam-tradeoffers/index.js:460:16)
    at Request.self.callback (/Users/*****/node_modules/steam-tradeoffers/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/*****/node_modules/steam-tradeoffers/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/*****/node_modules/steam-tradeoffers/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
This is my code:

``` javascript
trade.getOffers({
		"get_received_offers": 0,
		"get_sent_offers": 1,
		"active_only": 0,
		"time_historical_cutoff": Math.floor(Date.now() / 1000) - 1800
	}, function (err, offerhist) {
		if (err !== null) {
			resolvesentoffertimer = setTimeout(resolveSentOffers, 10000);
		} else {
			try {
				offerhist.response.trade_offers_sent.forEach(function (offer) {
					if (offer.trade_offer_state === 3) {
						existTrade(offer.tradeofferid, function (result) {
							if (result > 0) {
								console.log(offer.tradeofferid);
								trade.getItems({
									tradeId: offer.tradeofferid
								}, function (err, items) {
									if (err) throw err;
									items.forEach(function (item) {
										console.log(item);
									});
								});
							}
						});
				});
				resolvesentoffertimer = setTimeout(resolveSentOffers, 10000);
			} catch (e) {
				//not important, usually because no offers.
			}
		}
});
```
Maybe I didn't understand the main idea about this function.

My main idea is get the new assetid of the items in my inventory, after that the other user accepted my offer with his items, and which in his inventory they had another assetid. How can I do it?

**Comment by Yashko** [comment]
Looks like you dont logined with your bot. Send please full code

**Comment by Commanche2** [comment]
Of course I do, it's the first thing it does, as soon starts:

``` javascript
var logOnOptions = {
	accountName: username,
	password: password
};

bot.logOn(logOnOptions);

bot.on('loggedOn', function() {
	logger.info(displayName+' Logged on Steam');
	if (displayNamePrefix != '') {
		bot.setPersonaName(displayName);
	} else {
		bot.setPersonaName(displayNamePrefix+displayName); // to change its nickname
	}
	// Make sure we're not displaying as online until we're ready
});

bot.on('webSessionID', function(sessionID) {
	bot.webLogOn(function(newCookie){
		trade.setup({
			sessionID: sessionID,
			webCookie: newCookie
		});
		logger.info('Logged into web to make trades (Steam Community)');
		bot.setPersonaState(steam.EPersonaState.Online);
		findNewTradeAsync();
		resolveSentOffers();
		resolveReceivedOffers();
	});
});
```
Trust me, I do it all right, because it can make offers, accepting offers and more. If it wasn't logged in, it couldn't do all the previous staff.

I can't post all my code. It's too much code.

**Comment by protzi** [comment]
`
trade.setup({
            sessionID: sessionID,
            webCookie: newCookie,
            APIKey: ?
        });
`
