### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MrXromik** [Alex7Kom/node-steam-tradeoffers#112]
/root/BotSteam/examples/storehouse.js:51
      if(body.response.trade_offers_received){
             ^
TypeError: Cannot read property 'response' of undefined
    at /root/BotSteam/examples/storehouse.js:51:14
    at Object.doAPICall.bind.callback (/root/BotSteam/index.js:264:16)
    at SteamTradeOffers.<anonymous> (/root/BotSteam/index.js:241:17)
    at Request.self.callback (/root/BotSteam/node_modules/request/request.js:368:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/BotSteam/node_modules/request/request.js:1219:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/root/BotSteam/node_modules/request/request.js:1167:12)

Pls help

**Comment by Lwatt** [comment]
I'm getting this error at the moment as well

**Comment by Lwatt** [comment]
Turns out this is an error related to not having an steamcommunity web API key - go to steamcommunity.com/dev/apikey to register for one - I'd deleted my key by accident and got the same error. You don't need to do anything with the key, just make sure you have registered for one.

**Comment by MrXromik** [comment]
I fixed this problem. I register apikey.
