### ISSUE TITLE
loadMyInventory giving errors!

### ISSUE THREAD

**Issue by scyllaelemental** [Alex7Kom/node-steam-tradeoffers#131]
```javascript
offers.loadMyInventory(730, 2, function (err, items,d,a) {
    var item;
    // picking first tradable item just want to try if it works but it doesn't
    for (var i = 0; i < items.length; i++) {
        if (items[i].tradable) {
            item = items[i];
            break;
        }
    };
    logger.info(item.id);//log in the file and write on console 
});
```
i couldn't done that because of those errors :-1: 

    C:\Users\Scylla\Desktop\CrateDump>node ornek.js
     info: Logged on to Steam
     C:\Users\Scylla\Desktop\CrateDump\node_modules\steam-tradeoffers\index.js:160
            return callback(new Error('Invalid Response'));
                  ^
     TypeError: number is not a function
        at SteamTradeOffers.<anonymous> (C:\Users\Scylla\Desktop\CrateDump\node_modu
    les\steam-tradeoffers\index.js:160:14)
        at Request.self.callback (C:\Users\Scylla\Desktop\CrateDump\node_modules\ste
    am-tradeoffers\node_modules\request\request.js:197:22)
        at Request.emit (events.js:110:17)
        at Request.<anonymous> (C:\Users\Scylla\Desktop\CrateDump\node_modules\steam
     -tradeoffers\node_modules\request\request.js:1050:14)
        at Request.emit (events.js:129:20)
        at IncomingMessage.<anonymous> (C:\Users\Scylla\Desktop\CrateDump\node_modul
    es\steam-tradeoffers\node_modules\request\request.js:996:12)
        at IncomingMessage.emit (events.js:129:20)
        at _stream_readable.js:908:16
        at process._tickCallback (node.js:355:11)

**Comment by Alex7Kom** [comment]
`loadMyInventory` accepts an object as the first param and the second param must be a callback. Please read the docs more carefully.
