### ISSUE TITLE
storehouse.js TypeError: undefined is not a function

### ISSUE THREAD

**Issue by GuidoRumi** [Alex7Kom/node-steam-tradeoffers#137]
By running storehouse.js directly without modifications, I get this error:

node storehouse.js
/home/guido/node-steam-tradeoffers/examples/storehouse.js:32
var steamUser = new Steam.SteamUser(steamClient);
                ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/guido/node-steam-tradeoffers/examples/storehouse.js:32:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by scholtzm** [comment]
Make sure you are using node-steam 1.0.0

**Comment by GuidoRumi** [comment]
You were right, I reinstalled steam-tradeoffers and forgot to install steam. 

Now I'm getting:

node storehouse.js
/home/guido/node_modules/steam-tradeoffers/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:2539
                            throw Error(this+"#"+keyOrObj+" is not a field: un
                                                         ^
Error: .CMsgClientLogon#accountName is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/home/guido/node_modules/steam-tradeoffers/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:2539:58)
    at MessagePrototype.set (/home/guido/node_modules/steam-tradeoffers/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:2533:38)
    at Message (/home/guido/node_modules/steam-tradeoffers/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:2462:34)
    at SteamUser.logOn (/home/guido/node_modules/steam-tradeoffers/node_modules/steam/lib/handlers/user/index.js:33:6)
    at SteamClient.<anonymous> (/home/guido/node_modules/steam-tradeoffers/examples/storehouse.js:39:13)
    at SteamClient.emit (events.js:104:17)
    at SteamClient.handlers.(anonymous function) (/home/guido/node_modules/steam-tradeoffers/node_modules/steam/lib/steam_client.js:253:8)
    at SteamClient._netMsgReceived (/home/guido/node_modules/steam-tradeoffers/node_modules/steam/lib/steam_client.js:167:26)
    at Connection.emit (events.js:107:17)

This is my  npm list --depth=0
steam-tradeoffers@2.0.0 /home/guido/node_modules/steam-tradeoffers
├── cheerio@0.19.0
├── long@2.2.5
├── request@2.59.0
├── steam@1.0.0 extraneous
├── steam-web-api-key@0.0.1 extraneous
└── steam-weblogon@0.0.3 extraneous

**Comment by Alex7Kom** [comment]
Make sure you specify `account_name`, not `accountName`.

**Comment by GuidoRumi** [comment]
Once again, you were right. 
Thanks for your time

**Comment by madlybong** [comment]
Have tried both of the solutions.. still getting same error !
