### ISSUE TITLE
getItems not working

### ISSUE THREAD

**Issue by matrix14** [Alex7Kom/node-steam-tradeoffers#159]
getItems() not working?

it's my function.

```
offers.getItems({
	tradeId: tradeId
}, function(error, tradedata) {
	if (!error) {
		console.log('TradeData');
		console.log(tradedata);
	} else { throw error; }
});
```

I am receiving this:

```
Error: No session
    at Request._callback (/usr/lib/node_modules/steam-tradeoffers/index.js:308:23)
    at Request.self.callback (/usr/lib/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/request/request.js:1063:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

But session must be ok, because I do offers.getOffer a few lines earlier, and it working. (Of course this function is in callback of callback getOffer)

**Comment by Alex7Kom** [comment]
> (Of course this function is in callback of callback getOffer)

Please show this code too.

**Comment by matrix14** [comment]
It's this code. In array witingTrades are tradeid to check.

```
function checkAwaitingTrades() {
	if(botTurnOff==0) {
		for(var i in waitingTrades) {
			offers.getOffer ({
				"tradeOfferId": waitingTrades[i]
			}, function(err, response) {
				if (err) {
					throw err;
				}
				var tradeId = waitingTrades[i];
				var offerState = response.response.offer.trade_offer_state;
				
				var connection = mysql.createConnection(db_access);

				connection.connect(function(err){
					if(!err) {
						//console.log("Database is connected ... \n\n");  
					} else {
						console.log(getTimeStamp()+"Error connecting database ... \n\n");  
					}
				});
				
				if(offerState==3) { //Accepted
					var items = response.response.offer.items_to_receive;
					
					offers.getItems({
						tradeId: tradeId
					}, function(error, tradedata) {
						if (!error) {
							console.log('TradeData');
							console.log(tradedata);
getItemsFullFromItemsId(items, function(data) {
						//Hidden code
					});
						} else { console.log(tradedata); throw error; }
					});
					
					
				} else if(offerState==4) { //Countered
					//Hidden code
				} else if(offerState==5) { //Expired
					//Hidden code
				} else if(offerState==7) { //Decline
					//Hidden code
				}
			});
		}
	}
}
```

**Comment by Alex7Kom** [comment]
`tradeId` and `tradeOfferId` are not the same thing. Check https://github.com/Alex7Kom/node-steam-tradeoffers#getitemsoptions-callback on how to obtain `tradeId`.
