### ISSUE TITLE
Error clearTimer not defined+ empty string

### ISSUE THREAD

**Issue by bagda391** [Alex7Kom/node-steam-tradeoffers#163]
Ok so on my CS:GO Jackpot website, when pot reaches 50 items I get this error in the bot's console:

https://gyazo.com/ddff76265cae94236ed58a3e1c87801b

Also sometimes I get this error too:

Error: number format error: empty string
    at Error (native)
    at Function.Long.fromString (C:\Users\Frederik\Desktop\bot\node_modules\steam-tradeoffers\node_modules\long\dist\Long.js:180:19)
    at toAccountId (C:\Users\Frederik\Desktop\bot\node_modules\steam-tradeoffers\index.js:376:15)
    at SteamTradeOffers.makeOffer (C:\Users\Frederik\Desktop\bot\node_modules\steam-tradeoffers\index.js:396:42)
    at Query._callback (C:\Users\Frederik\Desktop\bot\sell.js:160:13)
    at Query.Sequence.end (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
    at Query.EofPacket (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
    at Protocol._parsePacket (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\Parser.js:77:12)

**Comment by andrewda** [comment]
Are you serious?
