### ISSUE TITLE
This happens everytime 

### ISSUE THREAD

**Issue by madlybong** [Alex7Kom/node-steam-tradeoffers#200]
C:\steamnode\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2440
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

Error: .CMsgClientLogon#sha1_sentryfile is not a field: undefined
    at Error (native)
    at MessagePrototype.set (C:\steamnode\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2440:35)
    at MessagePrototype.set (C:\steamnode\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2434:38)
    at Message (C:\steamnode\node_modules\steam\node_modules\steam-resources\node_modules\protobufjs\dist\ProtoBuf.js:2363:34)
    at SteamUser.logOn (C:\steamnode\node_modules\steam\lib\handlers\user\index.js:33:6)
    at SteamClient.<anonymous> (C:\steamnode\app.js:46:13)
    at emitNone (events.js:67:13)
    at SteamClient.emit (events.js:166:7)
    at SteamClient.handlers.(anonymous function) (C:\steamnode\node_modules\steam\lib\steam_client.js:243:8)
    at SteamClient._netMsgReceived (C:\steamnode\node_modules\steam\lib\steam_client.js:157:26)

**Comment by andrewda** [comment]
You're using `sha1_sentryfile` instead of `sha_sentryfile` (read the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon)). This is also not related to node-steam-tradeoffers.
