### ISSUE TITLE
Error throw from undefined this._requestCommunity

### ISSUE THREAD

**Issue by lopataz** [Alex7Kom/node-steam-tradeoffers#224]
Steam API is currently down and my server's crashing because of this error

TypeError: Cannot read property 'get' of undefined
    at SteamTradeOffers.loadInventory (/home/..../node_modules/steam-tradeoffers/index.js:437:25)
  at SteamTradeOffers.loadMyInventory (/home/..../node_modules/steam-tradoffers/index.js:104:27)

**Comment by lopataz** [comment]
I guess this is because offers.setup isn't called because Steam is down. but maybe there should be added:
 if(this._requestCommunity !== undefined){
 and also
  if(this._requestAPI !== undefined){
