### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by fedorovvldmr** [Alex7Kom/node-steam-tradeoffers#231]
Sometimes I get an error:
```
/mypath/node_modules/steam-tradeoffers/index.js:477
this._requestAPI[httpMethod](params, function(error, response, body) {
^
TypeError: Cannot read property 'get' of undefined
at SteamTradeOffers.doAPICall (/mypath/node_modules/steam-tradeoffers/index.js:477:19)
at SteamTradeOffers.getOffers (/mypath/node_modules/steam-tradeoffers/index.js:141:23)
at getOffers (/mypath/steambot.js:2976:11)
at SteamUser. (/mypath/steambot.js:3757:3)
at emitOne (events.js:77:13)
at SteamUser.emit (events.js:169:7)
at SteamUser.handlers.(anonymous function) (/mypath/node_modules/steam/lib/handlers/user/index.js:71:8)
at SteamUser. (/mypath/node_modules/steam/lib/handlers/user/index.js:12:28)
at emitThree (events.js:102:20)
at SteamClient.emit (events.js:175:7)
error: Forever detected script exited with code: 1
```

node-steam-tradeoffers ver 3.0.1

**Comment by Alex7Kom** [comment]
Make sure you don't call any methods before setup.
