### ISSUE TITLE
Undocumented methods of CEcon_TradeOffer object?

### ISSUE THREAD

**Issue by iJamesPHP** [Alex7Kom/node-steam-tradeoffers#241]
I have an offer object that I've got using the following code:

`body.response.trade_offers_received.forEach(function(offer) {`

This 'offer' object is a CEcon_TradeOffer object if I'm not mistaken, however, when I try and access the method documented by steam as 'items_to_receive', I get nothing back but undefined from this method, here's my code:

```
 if (offer.trade_offer_state === 2) {
        
        jamesBug('msg: '+offer.message);
      	jamesBug('i2r: '+offer.items_to_receive.length);
      	jamesBug('pid: '+offer.steamid_other);
      	jamesBug('first item id: '+offer.items_to_recieve[0].assetid);

```

The length method works and correctly returns '1' in my console but I'm getting this output when it hits that last line:

```
[Sun, 28 Feb 2016 10:58:20 GMT] msg: 5699433 | This is an automatic trade generated by OPSkins. Security token: GdYpnl
[Sun, 28 Feb 2016 10:58:20 GMT] i2r: 1
[Sun, 28 Feb 2016 10:58:20 GMT] pid: 76561198173363965
/Users/James/Sites/SteamNode/run.js:77
      	jamesBug('first item id: '+offer.items_to_recieve[0].assetid);
      	                                                 ^

TypeError: Cannot read property '0' of undefined
    at /Users/James/Sites/SteamNode/run.js:77:57
    at Array.forEach (native)
    at /Users/James/Sites/SteamNode/run.js:65:43
    at Object.doAPICall.bind.callback (/Users/James/Sites/SteamNode/node_modules/steam-tradeoffers/index.js:163:7)
    at SteamTradeOffers.<anonymous> (/Users/James/Sites/SteamNode/node_modules/steam-tradeoffers/index.js:491:15)
    at Request.self.callback (/Users/James/Sites/SteamNode/node_modules/steam-tradeoffers/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/James/Sites/SteamNode/node_modules/steam-tradeoffers/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)

```
Thanks for help,

James

**Comment by Alex7Kom** [comment]
You have a typo in your code.

It should be `offer.items_to_receive[0].assetid`

not `offer.items_to_recieve[0].assetid`.

**Comment by iJamesPHP** [comment]
Thanks very much, sorted it.
