### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by CodeLuca** [Alex7Kom/node-steam-tradeoffers#249]
TypeError: Cannot read property 'length' of undefined

    App.Bot.offers.makeOffer({
      partnerSteamID: '225203589',
      itemsFromMe: [{
        'appid': 730,
        'contextId': 2,
        'amount': 1,
        'assetid': '5519906821'
      }],
      itemsFromThem: []
    }, function(err, offerid) {
      debug(err);
      res.send(offerid);
    });

**Comment by CodeLuca** [comment]
TypeError: Cannot read property 'length' of undefined
    at Function.fromString (/Users/luca/code/node_modules/long/dist/Long.js:203:16)
    at toAccountId (/Users/luca/code/node_modules/steam-tradeoffers/index.js:362:15)
    at SteamTradeOffers.makeOffer (/Users/luca/code/node_modules/steam-tradeoffers/index.js:260:42)
    at send (/Users/luca/code/tripleskinsbot/api/send.js:26:20)
    at Layer.handle [as handle_request] (/Users/luca/code/tripleskinsbot/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/luca/code/tripleskinsbot/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/luca/code/tripleskinsbot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/luca/code/tripleskinsbot/node_modules/express/lib/router/layer.js:95:5)
    at /Users/luca/code/tripleskinsbot/node_modules/express/lib/router/index.js:277:22
    at param (/Users/luca/code/tripleskinsbot/node_modules/express/lib/router/index.js:349:14)

**Comment by Alex7Kom** [comment]
#121
