### ISSUE TITLE
Long.js Problem :)

### ISSUE THREAD

**Issue by Xeroner** [Alex7Kom/node-steam-tradeoffers#250]
Hi there, when i'm sending an offer, from time to time i'm getting this :

`Error: number format error: empty string
    at Error (native)
    at Function.fromString (/var/www/csboxpl2/app/node_modules/steam-tradeoffers/node_modules/long/dist/Long.js:204:19)
    at toAccountId (/var/www/csboxpl2/app/node_modules/steam-tradeoffers/index.js:362:15)
    at SteamTradeOffers.makeOffer (/var/www/csboxpl2/app/node_modules/steam-tradeoffers/index.js:260:42)
    at null._onTimeout (/var/www/csboxpl2/app/socket.js:753:40)
    at Timer.listOnTimeout (timers.js:92:15)`

Whyyy?

**Comment by Alex7Kom** [comment]
It clearly means that from time to time you pass an empty string as `partnerSteamId`.

**Comment by Xeroner** [comment]
Thanks dude :)
