### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by tuktun** [Alex7Kom/node-steam-tradeoffers#260]
Sometimes appears this exception:

```
/var/bot/node_modules/steam-tradeoffers/index.js:479
  this._requestAPI[httpMethod](params, function(error, response, body) {
                  ^
TypeError: Cannot read property 'get' of undefined
    at SteamTradeOffers.doAPICall (/var/bot/node_modules/steam-tradeoffers/index.js:479:19)
    at SteamTradeOffers.getOffers (/var/bot/node_modules/steam-tradeoffers/index.js:141:23)
    at getOffers (/var/bot/steambot.js:1813:11)
    at SteamUser.<anonymous> (/var/bot/steambot.js:2188:3)
    at SteamUser.emit (events.js:107:17)
    at SteamUser.handlers.(anonymous function) (/var/bot/node_modules/steam/lib/handlers/user/index.js:71:8)
    at SteamUser.<anonymous> (/var/bot/node_modules/steam/lib/handlers/user/index.js:12:28)
    at SteamClient.emit (events.js:129:20)
    at SteamClient._netMsgReceived (/var/bot/node_modules/steam/lib/steam_client.js:172:10)
    at SteamClient.handlers.(anonymous function) (/var/bot/node_modules/steam/lib/steam_client.js:259:10)
```
Please, fix this.

**Comment by andrewda** [comment]
When does this happen?

**Comment by tuktun** [comment]
Sometimes i have this exception when accepting trade offer.

Bot is logged and is web-logged.

```
offers.acceptOffer({tradeOfferId: offer.tradeofferid}, function(err, res) {
    if (err) {
		
	} else{
	
	} 
});
```

**Comment by Alex7Kom** [comment]
Double check that you call any methods after `setup()`.
And you can't get this exception when calling `acceptOffer()`, because it doesn't call `_requestAPI()`.

**Comment by andrewda** [comment]
I'm guessing this occurs when you make any sort of API request before calling the `setup()` method. Make sure you've called `setup()` before doing anything else.

**Comment by tuktun** [comment]
Yes, I did not notice that my app restarts and started handling offers before `setup()`
Thank Alex7Kom and andrewda for help.
