### ISSUE TITLE
TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by tuktun** [Alex7Kom/node-steam-tradeoffers#261]
Please, fix this.
```
 /var/bot/node_modules/steam-tradeoffers/index.js:446
    if (response.statusCode !== 200) {
                ^
TypeError: Cannot read property 'statusCode' of undefined
    at SteamTradeOffers.<anonymous> (/var/bot/node_modules/steam-tradeoffers/index.js:446:17)
    at self.callback (/var/bot/node_modules/request/request.js:198:22)
    at Request.emit (events.js:107:17)
    at null._onTimeout (/var/bot/node_modules/request/request.js:811:12)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by Alex7Kom** [comment]
When does this happen? It is strange that there is no `error` but response is `undefined`.

**Comment by andrewda** [comment]
I agree, this is strange. I have, however, witnessed this happen a few times making requests, but it's incredibly rare.

**Comment by Alex7Kom** [comment]
Should be fixed in https://github.com/Alex7Kom/node-steam-tradeoffers/commit/89f1e04eae23b959265cfe3477d4cd0973220a0d.
