### ISSUE TITLE
Error Cannot Read property 'get' of undefined

### ISSUE THREAD

**Issue by simonbt6** [Alex7Kom/node-steam-tradeoffers#289]
When i do nodejs, i get this error:
 Error: Cannot read property 'get' of undefined
    at SteamTradeOffers.doAPICall (/var/www/bot/node_modules/steam-tradeoffers/index.js:477:19)
    at SteamTradeOffers.getOffers (/var/www/bot/node_modules/steam-tradeoffers/index.js:141:23)
    at SteamUser.checkoffers (/var/www/bot/bot.js:944:16)
    at emitOne (events.js:77:13)
    at SteamUser.emit (events.js:169:7)
    at /var/www/bot/node_modules/steam-user/components/notifications.js:25:9
    at Array.forEach (native)
    at SteamUser._handlers.(anonymous function) (/var/www/bot/node_modules/steam-user/components/notifications.js:23:29)
    at SteamUser._handleMessage (/var/www/bot/node_modules/steam-user/components/messages.js:165:29)
    at emitThree (events.js:97:13)

**Comment by cymruu** [comment]
@simonbt6 you're getting property "get" of not defined variable.

**Comment by simonbt6** [comment]
Thanks but I already solved my problem and it's just that I didn't restart
my apache.

2017-03-24 10:17 GMT-04:00 filip <notifications@github.com>:
