### ISSUE TITLE
Error "Missing required parameter"

### ISSUE THREAD

**Issue by SteamTrade2017** [Alex7Kom/node-steam-tradeoffers#298]
Hello everybody!
I encountered such a problem when using a library for game H1Z1: King of the Kill (game id: 433850):

```
[2017-07-05 16:53:51.175] [DEBUG] [default] - [Error: missing required parameter]
Error: missing required parameter
at SteamTradeOffers.<anonymous> (/var/www/bot/node_modules/steam-tradeoffers/index.js:451:23)
at Request.self.callback (/var/www/bot/node_modules/request/request.js:188:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request.<anonymous> (/var/www/bot/node_modules/request/request.js:1171:10)
at emitOne (events.js:77:13)
at Request.emit (events.js:169:7)
at IncomingMessage.<anonymous> (/var/www/bot/node_modules/request/request.js:1091:12)
at IncomingMessage.g (events.js:260:16)
at emitNone (events.js:72:20)
```

I tried some solutions, but it did not help.
Trade Offer successfully sent, but I see this error.

My code:
```  
var assetids = req.query['assetids'];
  assetids = assetids.split(',');
  var partner = req.query['partner'];
  var token = req.query['token'];
  var checksum = req.query['checksum'];
  var steamid = req.query['steamid'];  
  var senditems = [];
  for (var i = 0; i < assetids.length; i++) {
    if (assetids[i] == "") continue;
    senditems.push({
      appid: 433850,
      contextid: 1,
      assetid: assetids[i]
    });
  }
  var code = makecode();
  console.log(partner, token, checksum, assetids, senditems);
  offers.makeOffer({
    partnerAccountId: partner,
    accessToken: token,
    itemsFromThem: senditems,
    itemsFromMe: [],
    message: code
  }, function(err, r) {
    if (err) {
      logger.error('Error sending trade');
      logger.debug(err);
      res.json({
        success: false,
        error: err.toString()
      });
    } else {
      offers.loadPartnerInventory({
        partnerSteamId: steamid,
        tradeOfferId: r.tradeofferid,
        appId: 433850,
        contextid: 1,
        language: 'russian'
      }, function(err, rr) {
        if (err) {
          logger.debug(err);
          res.json({
            success: false,
            error: err.toString()
          });
        } else {
          var names = [];
          for (var i = 0; i < senditems.length; i++) {
            for (var a = 0; a < rr.length; a++) {
              if ((senditems[i].assetid == rr[a].id) && (!rr[a].ss)) {
                names.push({
                  market_hash_name: rr[a].market_hash_name,
                  icon_url: rr[a].icon_url
                });
                rr[a].ss = 1;
                continue;
              }
            }
          }
          res.json({
            success: true,
            code: code,
            amount: checksum,
            tid: r.tradeofferid,
            items: names
          });
        }
      });
    }
  });
```

What am I doing wrong? Thank you in advance for your cooperation.

**Comment by andrewda** [comment]
Not sure if it's the only issue, but in your `loadPartnerInventory` call, you're using `contextid` when you should be using `contextId` (note the capitalized "I").

In the future, use three back ticks to format your code on GitHub so it doesn't end up looking like spaghetti (i.e. \`\`\` instead of a single \`). See: https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks
