### ISSUE TITLE
loadInventory get err: missing required parameter

### ISSUE THREAD

**Issue by raphaelsoul** [Alex7Kom/node-steam-tradeoffers#306]
I've solved automatic logon when disconnected by steam. 

But I got Error 'missing required parameter' when I call `loadPartnerInventory`. I double checked my params. It is good as document claims.

If I restart the process. It is good. This method should go through web interface on steam community. Is there anything else cause this error ? or caused by param type?

trace below:
```
// output of params
{ appId: '730',
  partnerSteamId: '<partnerSteamId>',
  language: 'english'
  contextId: '2' }

// out put of error
error:  Error: missing required parameter
    at _TradeOffers.<anonymous> (/app/node_modules/steam-tradeoffers/index.js:451:23)
    at Request.self.callback (/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by Alex7Kom** [comment]
This error comes from Steam, and Steam requires `tradeOfferId` if partner inventory is private.

**Comment by raphaelsoul** [comment]
The partner's inventory is public.

I read the code of dependency and did some debug tracing. 
I guess maybe the `sessionID` is expired and got failed when retrieving web sessions after reconnect. Cause it is the only parameter I am not sure if works.
But it's a little bit hard to reproduce. 
Please have some patient to close this issue. I need some time to figure it out.
