### ISSUE TITLE
Login not Working

### ISSUE THREAD

**Issue by spyfly** [Alex7Kom/node-steam-tradeoffers#65]
Hello, I got a Problem with logging in into the example bots. This is what I get after inserting the SteamGuard Code: 

connected
encrypt request
handshake complete
logon fail: 65, sessionID: 20601331

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Logon fail: 65
    at SteamClient.handlers.(anonymous function) (/home/pi/TradeBot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/home/pi/TradeBot/node_modules/steam/lib/steam_client.js:102:26)
    at SteamClient.handlers.(anonymous function) (/home/pi/TradeBot/node_modules/steam/lib/steam_client.js:188:10)
    at SteamClient._netMsgReceived (/home/pi/TradeBot/node_modules/steam/lib/steam_client.js:102:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (/home/pi/TradeBot/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)

How can this be fixed?

**Comment by Alex7Kom** [comment]
Not related to `node-steam-tradeoffers`.

**Comment by spyfly** [comment]
When I usw the Steam-Node Example, It is able to connect. Only the Steam-Tradeoffers doesn't works to login. Before this, it Bad a Problem with the sentryfile, it said something with "fs" is not defined.

**Comment by Alex7Kom** [comment]
Thank you for reminding about `fs`, this is now fixed in https://github.com/Alex7Kom/node-steam-tradeoffers/commit/bec517d07d131d46713e15e908bd219b990f4da7. I suspect this was the issue since sentry file wasn't written and auth code expired in the end.

**Comment by spyfly** [comment]
Thank you. It works now.

**Comment by patrys666** [comment]
@spyfly How did you fix this problem? Please help.

**Comment by scholtzm** [comment]
Error 65 is invalid auth code.

**Comment by patrys666** [comment]
I'm not sure I'm doing it well. I try to login via node, waiting for auth code, adding authcode to file and run it again.  What am I doing wrong?

**Comment by patrys666** [comment]
Also, how to generate ssfn file?

**Comment by spyfly** [comment]
You get the ssfn from your Steam Folder.

patrys666 <notifications@github.com> schrieb am Fr., 31. Juli 2015 18:44:
