### ISSUE TITLE
loadPartnerInventory error

### ISSUE THREAD

**Issue by pmk010** [Alex7Kom/node-steam-tradeoffers#74]
When attempting to loadPartnerInventory I receive the following error:
```
TypeError: Cannot read property 'length' of undefined
    at Function.Long.fromString (F:\Nodejs Steam\<edited>\node_modules\steam-tra
deoffers\node_modules\long\dist\Long.js:179:16)
    at toAccountId (F:\Nodejs Steam\<edited>\node_modules\steam-tradeoffers\inde
x.js:338:15)
    at SteamTradeOffers.loadPartnerInventory (F:\Nodejs Steam\<edited>\node_modu
les\steam-tradeoffers\index.js:185:82)
    at calcTradeValue (F:\Nodejs Steam\<edited>\Bot 1.js:294:10)
    at F:\Nodejs Steam\<edited>\Bot 1.js:383:22
    at Array.forEach (native)
    at F:\Nodejs Steam\<edited>\Bot 1.js:376:37
    at Object.doAPICall.callback (F:\Nodejs Steam\<edited>\node_modules\steam-tr
adeoffers\index.js:255:11)
    at Request._callback (F:\Nodejs Steam\<edited>\node_modules\steam-tradeoffer
s\index.js:226:17)
    at Request.self.callback (F:\Nodejs Steam\<edited>\node_modules\request\requ
est.js:373:22)

F:\Nodejs Steam\<edited>>PAUSE
Press any key to continue . . .
```

I currently call it like this, with partnerid being a 64bit Steam ID:
```
		offers.loadPartnerInventory(partnerid, 440, 2, function(inv) {
			//do stuff
		});
```
The issue seems to be linked with the Long.js module, I was hopeing that someone here could help.

Many thanks

**Comment by Alex7Kom** [comment]
You should pass to `loadInventory` an object with options, see [this example](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/offerbot.js#L40) and [docs](https://github.com/Alex7Kom/node-steam-tradeoffers#loadpartnerinventoryoptions-callback).

**Comment by andrewda** [comment]
I was getting the same error as pmk010, but then I realized I entered the `partnerID` as an integer. Try writing it as a string, `'1234567890'`, for example.

**Comment by pmk010** [comment]
Oh, that was silly of me. Thank you very much Alex.
