### ISSUE TITLE
Error on "steam.on('webSessionID', function(id)...

### ISSUE THREAD

**Issue by RakouskyS** [Alex7Kom/node-steam-tradeoffers#75]
steam = the steamClient() here.

>steam.on('webSessionID', function(id) {
  steam.webLogOn(function(newCookie){
    offers.setup({
      sessionID: id,
      webCookie: newCookie
    });
  });
});

Once this gets called, I get this error:

>c:\Users\sandro\steambot\node_modules\steam\lib\handlers\user.js:106
          'steamLogin=' + response.authenticateuser.token,
                                  ^
TypeError: Cannot read property 'authenticateuser' of null
    at IncomingMessage.<anonymous> (c:\Users\sandro\steambot\node_modules\steam\
lib\handlers\user.js:106:35)
    at IncomingMessage.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at onEofChunk (_stream_readable.js:401:3)
    at readableAddChunk (_stream_readable.js:146:7)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnMessageComplete (_http_common.js:154:14)
    at TLSSocket.socketOnData (_http_client.js:310:20)
    at TLSSocket.emit (events.js:107:17)

Any idea on how to fix this?

**Comment by Alex7Kom** [comment]
You should install [node-steam](https://github.com/seishun/node-steam) from git, because the npm version is old and doesn't support node.js 0.12 / io.js.
See also: https://github.com/seishun/node-steam/issues/115

This is not a `steam-tradeoffers` error, so I'm closing this anyway.
