### ISSUE TITLE
Error: Cannot find module 'core-util-is'

### ISSUE THREAD

**Issue by andrewda** [Alex7Kom/node-steam-tradeoffers#83]
When I try to run even the default offerbot, I get the following error. Note that I just upgraded to the latest versions of Node-Steam and Node-Steam-Tradeoffers as I wasn't quite caught up.
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/request/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:39:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by ldd91** [comment]
How did you solved this error @andrewda . I met the same error
